### ISSUE TITLE
Allow embed by path

### ISSUE THREAD

**Issue by lrvick** [gengo/github-commit-embed#1]
If you combine a couple APIs you can get the direct blob URLs automatically using only the username and path as inputs, thus avoiding the requirement of looking up hashes for files.

You can grab the URL to the latest tree via: http://api.github.com/repos/:user/:repo/commits

Just add '?recursive=true' the first tree URL and you end up with:

https://api.github.com/repos/:user/:repo/git/trees/:sha?recursive=true

You can then search that tree for the inputted path and grab the direct blob URL to the latest version, then do your base64 decoding and what not from there.

I have implemented this setup in my simple tree-navigation project here: https://github.com/lrvick/jquery-githubnav

**Comment by ryanmcgrath** [comment]
This is true, but the reason I went with hashes in the original is that we use it in our API documentation at myGengo, and I had concerns about possible rate limiting issues with regards to the client (side) loading resources from GitHub's servers. 

I'm down to actually just support both styles here though, let me see if I can find some time to work it in.

Thanks!

**Comment by lrvick** [comment]
I wondered about API limits as well for my implementations. 

I did a bit of testing to be sure how those are bound:

For all unauthenticated requests rate limits fall back to being bound to the requesting IP only.
Each IP gets 5000 API calls per hour. At 3 calls to render each file that's ~1666 snippets loaded per hour per IP.  

For an individual user this is of course plenty unless someone is intentionally abusing a page which would only get themselves limited.

Access to private repositories requires Oauth login which then gives each individual client its own pool of 5000 which allows even more.

If there was however a situation where a site with an embed was going to be used heavily in an corporate office environment with one outbound IP, you could avoid rate-limiting by tossing the result in a localStorage key with an expiry of one hour for each browser so the same requests can not be made more than once per client per hour, but instead just load from the cached key. Only about 4 lines of code for that so it might not be a bad thing to consider anyway to be nice to Githubs APIs.

Anyway, just food for thought :-)

**Comment by ryanmcgrath** [comment]
Oh, the rate limit is 5000? I read 1000 somewhere at one point... thanks for the heads up! Your method is way better, will roll it in shortly.

**Comment by lrvick** [comment]
closed as project appears dead.
